language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

before_script:
  - npm install -g gulp

script: gulp test

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"