language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

before_script:
  - npm install -g gulp

script: npm test

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"